import pulp as plp
from numpy.typing import NDArray

from mapc_optimal.utils import OptimizationType


class Main:
    r"""
    The main problem responsible for the selection and time division of configurations
    generated by the pricing problem.
    """

    def __init__(
            self,
            min_throughput: float,
            log_approx: tuple[NDArray, NDArray],
            opt_type: OptimizationType,
            solver: plp.LpSolver
    ) -> None:
        r"""
        Parameters
        ----------
        min_throughput : float
            The minimum throughput of each station required when optimizing total throughput.
        log_approx : tuple[NDArray, NDArray]
            Tuple containing the slopes and biases of the piecewise linear approximation of the logarithm function.
        opt_type : OptimizationType
            The type of optimization problem to solve.
        solver : pulp.LpSolver
            The solver used to solve the optimization problem.
        """

        self.min_throughput = min_throughput
        self.log_approx = log_approx
        self.opt_type = opt_type
        self.solver = solver

    def __call__(
            self,
            stations: list,
            link_node_b: dict,
            conf_links: dict,
            conf_link_rates: dict,
            conf_total_rates: dict,
            confs: list
    ) -> tuple[dict, float]:
        """
        Solves the main problem given the configurations generated by the pricing problem.
        Returns the dual variables, the shares of the configurations and the value of the objective function.

        Parameters
        ----------
        stations : list
            List of the station nodes.
        link_node_b : dict
            Dictionary containing the mapping of links to the station nodes.
        conf_links : dict
            Dictionary containing the links of each configuration.
        conf_link_rates : dict
            Dictionary containing the rates of each link for each configuration.
        conf_total_rates : dict
            Dictionary containing the total rate of each configuration.
        confs : list
            List of the configurations.

        Returns
        -------
        result : tuple[dict, float]
            Tuple containing the results of the optimization problem and the value of the objective function.
        """

        main = plp.LpProblem('main', plp.LpMaximize)

        conf_weight = plp.LpVariable.dicts('conf_weight', confs, lowBound=0, upBound=1, cat=plp.LpContinuous)
        node_throughput = plp.LpVariable.dicts('node_throughput', stations, lowBound=0, cat=plp.LpContinuous)
        min_throughput = plp.LpVariable('min_throughput', lowBound=0, cat=plp.LpContinuous)
        log_approx = plp.LpVariable.dicts('log_approx', stations, cat=plp.LpContinuous)

        # fraction of time when we use the configuration, the sum of all the weights is 1
        main += plp.lpSum(conf_weight[c] for c in confs) == 1, 'conf_weight_c'  # dual: alpha

        for s in stations:
            # calculation of the summarized throughput of each station (over all the used configurations)
            main += node_throughput[s] == plp.lpSum(
                conf_link_rates[c][l] * conf_weight[c] for c in confs for l in conf_links[c] if link_node_b[l] == s
            ), f'node_throughput_{s}_c'  # dual: beta

            # calculation of the worst throughput (this constraint is especially necessary for max-min optimization)
            main += node_throughput[s] >= min_throughput, f'worst_throughput_{s}_c'  # dual: gamma

            # approximation of the logarithm function
            for k, (a, b) in enumerate(zip(*self.log_approx)):
                main += log_approx[s] <= a * node_throughput[s] + b, f'log_approx_{s}_{k}_c'

        if self.opt_type == OptimizationType.SUM:
            # enforcement of the minimum throughput of each station
            main += min_throughput >= self.min_throughput, f'min_throughput_c'

        if self.opt_type == OptimizationType.SUM:
            # maximization of the total throughput
            main += plp.lpSum(conf_total_rates[c] * conf_weight[c] for c in confs), 'total_throughput_g'
        elif self.opt_type == OptimizationType.MAX_MIN:
            # maximization of the worst throughput
            main += min_throughput, 'min_throughput_g'
        elif self.opt_type == OptimizationType.PROPORTIONAL:
            # maximization of the sum of the logarithms of the throughputs
            main += plp.lpSum(log_approx[s] for s in stations), 'log_throughput_g'
        else:
            raise ValueError('Invalid optimization type')

        main.conf_weight = conf_weight

        main.solve(self.solver)

        if main.status != plp.LpStatusOptimal:
            raise Exception('Main problem not solved optimally')

        result = {
            'alpha': main.constraints['conf_weight_c'].pi,
            'beta': {s: main.constraints[f'node_throughput_{s}_c'].pi for s in stations},
            'gamma': {s: main.constraints[f'worst_throughput_{s}_c'].pi for s in stations},
            'shares': {c: main.conf_weight[c].varValue for c in confs}
        }

        return result, plp.value(main.objective)
